Create rules for migration to Hibernate 5.6
konveyor/rulesets pull request #206
Opened 2024-12-20 17:29 UTC by jayfray12

- Create rule to detect javassist
- Create rule to detect use of type CLOB in PostgresSQL81Dialect

These were the only 2 items found in the hibernate [migration guide](https://github.com/hibernate/hibernate-orm/blob/5.6/migration-guide.adoc)

2025-01-07 10:55 UTC, jmle requested changes
Looks good, just some minor requests

2025-01-07 10:55 UTC, jmle commented on default/generated/spring-framework/spring-framework-5.x-to-6.0-data-access.yaml
> +        pattern: hibernate.bytecode.provider=javassist
I think this pattern would only be valid for `*.properties` files, right?

2025-01-07 10:55 UTC, jmle commented on default/generated/spring-framework/spring-framework-5.x-to-6.0-data-access.yaml
> +    - as: hibernate_cfg
I think we can remove this `as` field, since it's now being used anywhere. The same with the one below, `as: persistence_files`.

2025-01-07 10:55 UTC, jmle commented on default/generated/spring-framework/spring-framework-5.x-to-6.0-data-access.yaml
> +      - as: config_files # Check for PostgreSQL 8.1 dialect
We don't need this `as` field. This is basically used when the outcome of a subcondition is needed in the next subcondition, providing some sort of "chaining", but here is not necessary.

2025-01-07 10:55 UTC, jmle commented on default/generated/spring-framework/spring-framework-5.x-to-6.0-data-access.yaml
> +          pattern: org.hibernate.dialect.PostgreSQL81Dialect
Should we add a subcondition looking for PostgreSQL dependency too, or would it be enough with this? Not sure if this property is always used. If we don't need the dep condition, then better.

2025-01-07 10:55 UTC, jmle commented on default/generated/spring-framework/spring-framework-5.x-to-6.0-data-access.yaml
> +    Consider reviewing DDL generation for CLOB columns and potential migration to 'oid' type if necessary.
I would add some information about this potential data loss, which looks quite worrying:

```
All PostgreSQL JDBC drivers unfortunately just store the oid it created for a java.sql.Clob into the text column. Although reading back the value with the CLOB API works, PostgreSQL has no knowledge of the reference to the LOB, because the oid is not known to PostgreSQL, leading to data loss when vacuumlo (the utility to clean up unused LOBs) runs. To avoid the data loss, it is required to use the oid type so that vacuumlo can see the reference.

Updating to 5.6.2 does not require any schema or application changes by default, but we highly recommend that you migrate existing text columns for LOBs to oid to prevent data loss due to the activity of vacuumlo.
```

2025-01-13 16:23 UTC, jayfray12 commented on default/generated/spring-framework/spring-framework-5.x-to-6.0-data-access.yaml
> +        pattern: hibernate.bytecode.provider=javassist
I believe you can set this in xml files as well (persistence.xml as well as I believe you can use application.xml instead of application.properties).  I know it isn't used all that often but figured why not.  Let me know if you want me to just change it to `*.properties`

2025-01-13 16:27 UTC, jayfray12 commented on default/generated/spring-framework/spring-framework-5.x-to-6.0-data-access.yaml
> +          pattern: org.hibernate.dialect.PostgreSQL81Dialect
That's a good question.  I've always configured it this way but never really looked into the other possible ways to configure.  I'll do that and report back

2025-01-13 19:07 UTC, jayfray12 commented on default/generated/spring-framework/spring-framework-5.x-to-6.0-data-access.yaml
> +          pattern: org.hibernate.dialect.PostgreSQL81Dialect
Based on research I have done it is best to have the dependency check in there.  I've added it

2025-01-13 19:07 UTC, jayfray12 commented on default/generated/spring-framework/spring-framework-5.x-to-6.0-data-access.yaml
> +      - as: config_files # Check for PostgreSQL 8.1 dialect
Removed

2025-01-13 19:07 UTC, jayfray12 commented on default/generated/spring-framework/spring-framework-5.x-to-6.0-data-access.yaml
> +    - as: hibernate_cfg
Removed

2025-01-13 19:07 UTC, jayfray12 commented on default/generated/spring-framework/spring-framework-5.x-to-6.0-data-access.yaml
> +    Consider reviewing DDL generation for CLOB columns and potential migration to 'oid' type if necessary.
Added

2025-01-14 12:40 UTC, jmle commented on default/generated/spring-framework/spring-framework-5.x-to-6.0-data-access.yaml
> +        pattern: hibernate.bytecode.provider=javassist
I'm at least sure that the pattern `hibernate.bytecode.provider=javassist` won't be detected in `*.yaml` files, since it would look more like
```yaml
hibernate:
  bytecode:
    provider: javassist
```
or simply `hibernate.bytecode.provider: javassist` with `:` instead of `=`. Not sure about the `persistence.xml` file, but it would probably look more like `<property name="hibernate.bytecode.provider">javassist</property>` or something similar maybe?

2025-01-14 12:44 UTC, jayfray12 commented on default/generated/spring-framework/spring-framework-5.x-to-6.0-data-access.yaml
> +        pattern: hibernate.bytecode.provider=javassist
True.  So the question is should I remove the xml and yaml portion or create another pattern?

2025-01-14 12:53 UTC, jayfray12 commented on default/generated/spring-framework/spring-framework-5.x-to-6.0-data-access.yaml
> +        pattern: hibernate.bytecode.provider=javassist
After thinking about it I don't believe that property would be in the persistence.xml file.  That's primarily JPA specific configs not hibernate.  So we could probably just change the rule to this:
```
- builtin.filecontent:
    filePattern: *.properties
    pattern: hibernate.bytecode.provider=javassist
- builtin.filecontent:
    filePattern: application\.yaml
    pattern: hibernate.bytecode.provider: javassist
 ```
 If your good with that I'll make the change or if you just think *.properties is good enough we could remove the application.yaml check.  Let me know

2025-01-16 08:51 UTC, jmle approved these changes

2025-01-16 10:24 UTC, merged